export const images = {
  IntroImage1: require('./IntroImage1.png'),
  IntroImage2: require('./IntroImage2.png'),
  IntroImage3: require('./IntroImage3.png'),
  IntroImage4: require('./IntroImage4.png'),
  SuccessLabel: require('./SuccessLabel.png'),
  FailedLabel: require('./FailedLabel.png'),
  background: require('./background.png'),
  MainBackground: require('./main-background.png'),
  Background2: require('./background2.png'),
  Test: require('./test.png'),
  IntroduceScreen: require('./introduceScreen.png'),
  FailedScreen: require('./FailScreen.png'),
  Avatar: require('./avata.png'),
  PremiumAvatar: require('./premium-avatar.png'),
  warning: require('./warning.png'),
  update: require('./update.png'),
  updateBackground: require('./update-back-ground.png'),
};
