export enum Screens {
  AuthenticationNavigator = 'AuthenticationNavigator',
  AuthenticatedNavigator = 'AuthenticatedNavigator',
  HomeStack = 'HomeStack',
  HomeScreen = 'HomeScreen',
  WordScreens = 'WordScreens',
  IntroduceScreen = 'IntroduceScreen',
  LoginScreen = 'LoginScreen',
  RegisterScreen = 'RegisterScreen',
  SettingsScreen = 'SettingsScreen',
  StorageWord = 'StorageWord',
  StorageStack = 'StorageStack',
  ArrangeWord = 'ArrangeWord',
  BottomTabNavigator = 'BottomTabNavigator',
  AddCategory = 'AddCategory',
  AddWord = 'AddWord',
  AddWordToStorage = 'AddWordToStorage',
  GetCodeScreen = 'GetCodeScreen',
  ResetPassword = 'ResetPassword',
  ChangePassword = 'ChangePassword',
  ResetPasswordStack = 'ResetPasswordStack',
  EnterPhoneNumber = 'EnterPhoneNumber',
  SettingStack = 'SettingStack',
}
